'\" t
.\"     Title: sourcehawk-scan
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2022-01-25
.\"    Manual: Sourcehawk Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "SOURCEHAWK\-SCAN" "1" "2022-01-25" "" "Sourcehawk Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
sourcehawk-scan \- Runs a Sourcehawk scan on the source code
.SH "SYNOPSIS"
.sp
\fBsourcehawk scan\fP [\fB\-hV\fP] [[\fB\-t\fP=\fI<tags>\fP]... [\fB\-v\fP=\fI<verbosity>\fP] [\fB\-f\fP=\fI<outputFormat>\fP] [\fB\-w\fP]
[[\fB\-c\fP=\fIconfig\-file\-path\fP] | \fB\-U\fP=\fIconfig\-file\-url\fP]]
[[\fIREPOSITORY\-ROOT\fP]] [COMMAND]
.SH "DESCRIPTION"
.sp
Runs a Sourcehawk scan on the source code
.SH "OPTIONS"
.sp
\fB\-c\fP, \fB\-\-config\-file\fP=\fIconfig\-file\-path\fP
.RS 4
The configuration file, can be relative, or absolute
.sp
.if n .RS 4
.nf
.fam C
Default: sourcehawk.yml
.fam
.fi
.if n .RE
.RE
.sp
\fB\-f\fP, \fB\-\-output\-format\fP=\fI<outputFormat>\fP
.RS 4
Output Format, valid values: TEXT, JSON, MARKDOWN
.sp
.if n .RS 4
.nf
.fam C
Default: TEXT
.fam
.fi
.if n .RE
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-t\fP, \fB\-\-tags\fP=\fI<tags>\fP
.RS 4
Tags of file protocols to limit the scope of execution
.RE
.sp
\fB\-U\fP, \fB\-\-config\-file\-url\fP=\fIconfig\-file\-url\fP
.RS 4
A remote URL which resolves to a configuration file
.RE
.sp
\fB\-v\fP, \fB\-\-verbosity\fP=\fI<verbosity>\fP
.RS 4
Verbosity of output, valid values: ZERO, LOW, MEDIUM, HIGH
.sp
.if n .RS 4
.nf
.fam C
Default: HIGH
.fam
.fi
.if n .RE
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information and exit.
.RE
.sp
\fB\-w\fP, \fB\-\-fail\-on\-warnings\fP
.RS 4
Whether to fail the scan if only warnings are found
.sp
.if n .RS 4
.nf
.fam C
Default: false
.fam
.fi
.if n .RE
.RE
.SH "ARGUMENTS"
.sp
[\fIREPOSITORY\-ROOT\fP]
.RS 4
The repository root on the file system to scan relative to, defaults to current directory
.RE
.SH "COMMANDS"
.sp
\fBhelp\fP
.RS 4
Displays help information about the specified command
.RE
.sp
\fBgithub\fP, \fBgh\fP
.RS 4
Runs a Sourcehawk scan on remote Github source code instead of local file system
.RE
.sp
\fBbitbucket\fP, \fBbb\fP
.RS 4
Runs a Sourcehawk scan on remote Bitbucket source code instead of local file system
.RE