name: 'Build Windows Native Image'
description: 'Build native image distribution for Windows'

inputs:
  jar-artifact-name:
    description: 'Name of the JAR artifact to download'
    default: 'native-image-jar'
    required: true
  java-version:
    description: 'Java Version'
    required: true
  graalvm-version:
    description: 'GraalVM Version'
    default: '20.3.0'
    required: true
  github-token:
    description: 'Github Token'
    required: true
  native-image-options:
    description: 'Options to pass to native-image build'
    default: '-H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime --gc=epsilon --no-fallback'
    required: false
  artifact-name:
    description: 'Name of the uploaded native image artifact'
    default: 'windows-native-image'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download Native Image JAR
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.jar-artifact-name }}
        path: build
    - name: Rename Native Image JAR
      working-directory: build
      shell: cmd
      run: ren *.jar native-image.jar
    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: ${{ inputs.graalvm-version }}
        java-version: ${{ inputs.java-version }}
        components: 'native-image'
        github-token: ${{ inputs.github-token }}
    - name: Build Windows Native Image
      if: success()
      shell: cmd
      run: native-image.cmd -cp .\build\native-image.jar ${{ inputs.native-image-options }}
    - name: Archive Windows Native Image
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact-name }}
        path: sourcehawk.exe
    - name: Smoke Test
      if: success()
      shell: cmd
      run: sourcehawk.exe help