name: Build and Push Docker Builders
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Github Ref'
        required: false
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PACKAGE_TOKEN }}
      - name: Build and Push graalvm-ce-21.3.0-java11
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-nativeimage
          build-args: FROM_VERSION=java11-21.3.0
          tags: ghcr.io/optum/ci/nativeimage:graalvm-ce-21.3.0-java11
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and Push graalvm-ce-21.3.0-java17
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-nativeimage
          build-args: FROM_VERSION=java17-21.3.0
          tags: ghcr.io/optum/ci/nativeimage:graalvm-ce-21.3.0-java17
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and Push rpmbuild centos7
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-rpmbuild
          build-args: FROM=centos:7
          tags: ghcr.io/optum/ci/rpmbuild:centos7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and Push rpmbuild centos8
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-rpmbuild
          build-args: FROM=centos:8
          tags: ghcr.io/optum/ci/rpmbuild:centos8
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and Push rpmbuild fedora33
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-rpmbuild
          build-args: FROM=fedora:33
          tags: ghcr.io/optum/ci/rpmbuild:fedora33
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and Push rpmbuild fedora34
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-rpmbuild
          build-args: FROM=fedora:34
          tags: ghcr.io/optum/ci/rpmbuild:fedora34
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and Push rpmbuild fedora35
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-rpmbuild
          build-args: FROM=fedora:35
          tags: ghcr.io/optum/ci/rpmbuild:fedora35
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Relocate Docker Layer Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
