name: Build and Push Docker Builders
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Github Ref'
        required: false
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Build and Push Docker Images to Github Container Registry
        shell: bash
        run: ./distributions/scripts/build-and-push-docker-builders.sh
        env:
          DOCKER_USERNAME: ${{ secrets.GIT_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
