name: Maven CI

on:
  push:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - 'install-*.sh'
      - '**/*.adoc'
      - '**/*.css'
      - '**/README.md'
  pull_request:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - 'install-*.sh'
      - '**/README.md'

env:
  PRIMARY_JAVA_VERSION: '11'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Maven Prepare
        id: maven-prepare
        uses: optum/sourcehawk/.github/actions/maven-prepare@workflow-updates
        with:
          java-version: ${{ matrix.java }}
      - name: Build Maven Project
        if: success() && (github.event_name == 'pull_request' || (github.event_name == 'push' && matrix.java != env.PRIMARY_JAVA_VERSION))
        run: ./mvnw --batch-mode install -D ci.build
      - name: Build Maven Project and Deploy Snapshots
        if: success() && (github.event_name == 'push' && matrix.java == env.PRIMARY_JAVA_VERSION)
        run: ./mvnw --batch-mode deploy -D ci.build -D ci.deploy -D ci.snapshot
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
      - name: Publish Test Report
        if: always()
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: test-report (${{ matrix.java }})
          path: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
          reporter: java-junit
      - name: Archive Native Image JAR
        if: success() && (matrix.java == env.PRIMARY_JAVA_VERSION)
        uses: actions/upload-artifact@v2
        with:
          name: native-image-jar
          path: cli/target/*-native-image.jar
      - name: Archive Completion Script
        if: success() && (matrix.java == env.PRIMARY_JAVA_VERSION)
        uses: actions/upload-artifact@v2
        with:
          name: completion-script
          path: cli/target/sourcehawk-completion.sh
      - name: Archive Manpages
        if: success() && (matrix.java == env.PRIMARY_JAVA_VERSION)
        uses: actions/upload-artifact@v2
        with:
          name: manpages
          path: gh-pages/manpages/sourcehawk*.1
      - name: Analyze with SonarCloud
        if: success() && (github.event_name == 'push' && matrix.java == env.PRIMARY_JAVA_VERSION)
        continue-on-error: true
        run: ./mvnw --batch-mode sonar:sonar -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  build-linux-native-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Download Manpages
        uses: actions/download-artifact@v2
        with:
          name: manpages
          path: gh-pages/manpages
      - name: Maven Prepare
        uses: optum/sourcehawk/.github/actions/maven-prepare@workflow-updates
        with:
          java-version: ${{ matrix.java }}
      - name: Build Native Image
        if: success() && (github.event_name == 'pull_request')
        run: ./mvnw --batch-mode install -D ci.build -D dist.build -pl distributions,distributions/linux
      - name: Build Native Image
        if: success() && (github.event_name == 'push')
        run: ./mvnw --batch-mode deploy -D ci.build -D ci.deploy -D ci.snapshot -D dist.build -pl distributions,distributions/linux
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
      - name: Publish Test Report
        if: always()
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: Linux Distributions Test Report
          path: 'distributions/linux/**/target/surefire-reports/TEST-*.xml,distributions/linux/**/target/failsafe-reports/TEST-*.xml'
          reporter: java-junit
      - name: Archive Linux Native Image
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: linux-native-image
          path: distributions/linux/target/sourcehawk
  build-linux-distribution:
    runs-on: ubuntu-latest
    needs: build-linux-native-image
    strategy:
      matrix:
        dist: ['debian', 'rpm', 'docker']
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Download Manpages
        uses: actions/download-artifact@v2
        with:
          name: manpages
          path: gh-pages/manpages
      - name: Maven Prepare
        uses: optum/sourcehawk/.github/actions/maven-prepare@workflow-updates
        with:
          java-version: 11
      - name: Build Distribution
        if: success() && (github.event_name == 'pull_request')
        run: ./mvnw --batch-mode install -D ci.build -D dist.build -D dist.build -pl distributions/${{ matrix.dist }}
      - name: Build Distributions and Publish Snapshots
        if: success() && (github.event_name == 'push')
        run: ./mvnw --batch-mode deploy -D ci.build -D ci.deploy -D ci.snapshot -D dist.build -pl distributions/${{ matrix.dist }}
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
      - name: Publish Test Report
        if: (matrix.java == env.PRIMARY_JAVA_VERSION)
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: Distribution Test Report (${{ matrix.dist }})
          path: distributions/${{ matrix.dist }}/target/surefire-reports/TEST-*.xml,distributions/${{ matrix.dist }}/target/failsafe-reports/TEST-*.xml
          reporter: java-junit
      - name: Archive Distribution
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: linux-dist-${{ matrix.dist }}
          path: distributions/${{ matrix.dist }}/target/**
  build-mac-native-image:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download Native Image JAR
        uses: actions/download-artifact@v2
        with:
          name: native-image-jar
          path: build
      - name: Rename Native Image JAR
        working-directory: build
        run: mv *.jar native-image.jar
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: ${{ env.PRIMARY_JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Mac Native Image
        if: success()
        working-directory: build
        run: native-image -cp native-image.jar -H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime --no-fallback
      - name: Archive Mac Native Image
        if: success()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: mac-native-image
          path: build/sourcehawk
      - name: Smoke Test
        if: success()
        working-directory: build
        run: ./sourcehawk help
  build-homebrew-tap-formula-archive:
    runs-on: macos-latest
    needs: build-mac-native-image
    steps:
      - name: Download Mac Native Image
        uses: actions/download-artifact@v2
        with:
          name: mac-native-image
          path: build
      - name: Download Completion Script
        uses: actions/download-artifact@v2
        with:
          name: completion-script
          path: build
      - name: Download Manpages
        uses: actions/download-artifact@v2
        with:
          name: manpages
          path: build
      - name: Create Homebrew Tap Formula Archive
        if: success()
        working-directory: build
        run: |
          chmod +x sourcehawk
          cp sourcehawk-completion.sh sourcehawk-bash-completion.sh
          cp sourcehawk-completion.sh sourcehawk-zsh-completion.sh
          chmod +x *.sh
          gzip sourcehawk*.1
          tar -cvf sourcehawk-homebrew-tap-formula.tar.gz sourcehawk*
      - name: Archive Homebrew Tap Formula Archive
        if: success()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-tap-formula-archive
          path: build/sourcehawk-homebrew-tap-formula.tar.gz
  build-windows-native-image:
    runs-on: windows-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Download Native Image JAR
        uses: actions/download-artifact@v2
        with:
          name: native-image-jar
          path: build
      - name: Rename Native Image JAR
        working-directory: build
        run: ren *.jar native-image.jar
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '20.3.0'
          java-version: ${{ env.PRIMARY_JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Windows Native Image
        if: success()
        run: native-image.cmd -cp .\build\native-image.jar -H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime
      - name: Archive Windows Native Image
        if: success()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: windows-native-image
          path: sourcehawk.exe
      - name: Smoke Test
        if: success()
        shell: cmd
        run: sourcehawk.exe help
