name: Maven CI

on:
  push:
    branches:
      - 'main'
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - 'install-*.sh'
      - '**/*.adoc'
      - '**/*.css'
      - '**/README.md'
  pull_request:
    branches:
      - 'main'
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - 'install-*.sh'
      - '**/README.md'

env:
  PRIMARY_JAVA_VERSION: '11'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    name: Build Java - ${{ matrix.java }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Maven Prepare
        id: maven-prepare
        uses: optum/sourcehawk/.github/actions/maven-prepare@main
        with:
          cache-key-suffix: build-java
          java-version: ${{ matrix.java }}
          gpg-private-key: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY }}
      - name: Build Maven Project
        if: success() && (github.event_name == 'pull_request' || (github.event_name == 'push' && matrix.java != env.PRIMARY_JAVA_VERSION))
        run: ./mvnw -B -U -D ci.build install
      - name: Build Maven Project and Deploy Snapshots to Sonatype OSSRH
        if: success() && (github.event_name == 'push' && matrix.java == env.PRIMARY_JAVA_VERSION)
        run: ./mvnw -B -U -D ci.build -D ci.deploy -D ci.snapshot deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
      - name: Publish Test Report
        if: always()
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: Test Report - Java ${{ matrix.java }}
          path: '**/target/(surefire|failsafe)-reports/TEST-*.xml'
          reporter: java-junit
      - name: Archive Native Image JAR
        if: success() && (matrix.java == env.PRIMARY_JAVA_VERSION)
        uses: actions/upload-artifact@v2
        with:
          name: native-image-jar
          path: cli/target/*-native-image.jar
      - name: Archive Completion Script
        if: success() && (matrix.java == env.PRIMARY_JAVA_VERSION)
        uses: actions/upload-artifact@v2
        with:
          name: completion-script
          path: cli/target/sourcehawk-completion.sh
      - name: Archive Manpages
        if: success() && (matrix.java == env.PRIMARY_JAVA_VERSION)
        uses: actions/upload-artifact@v2
        with:
          name: manpages
          path: gh-pages/manpages/sourcehawk*.1
      - name: Analyze with SonarCloud
        if: success() && (github.event_name == 'push' && matrix.java == env.PRIMARY_JAVA_VERSION)
        continue-on-error: true
        run: ./mvnw -B sonar:sonar -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  build-linux-native-image:
    runs-on: ubuntu-latest
    needs: build
    name: Build Native Image - Linux
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Download Manpages
        uses: actions/download-artifact@v2
        with:
          name: manpages
          path: gh-pages/manpages
      - name: Maven Prepare
        uses: optum/sourcehawk/.github/actions/maven-prepare@main
        with:
          cache-key-suffix: build-linux-native-image
          java-version: ${{ env.PRIMARY_JAVA_VERSION }}
      - name: Build Native Image
        if: success() && (github.event_name == 'pull_request')
        run: ./mvnw -B -U -D ci.build -D dist.build -pl distributions,distributions/linux install
      - name: Build Native Image
        if: success() && (github.event_name == 'push')
        run: ./mvnw -B -U -D ci.build -D ci.deploy -D ci.snapshot -D dist.build -pl distributions,distributions/linux deploy
      - name: Publish Test Report
        if: always()
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: Test Report - Linux Native Image
          path: 'distributions/linux/**/target/(surefire|failsafe)-reports/TEST-*.xml'
          reporter: java-junit
      - name: Archive Native Image
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: linux-native-image
          path: ${{ steps.build.outputs.native-image-path }}

  build-linux-distribution:
    runs-on: ubuntu-latest
    needs: build-linux-native-image
    strategy:
      matrix:
        dist: ['debian', 'rpm', 'docker']
    name: Build Linux Distribution - ${{ matrix.dist }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Download Manpages
        uses: actions/download-artifact@v2
        with:
          name: manpages
          path: gh-pages/manpages
      - name: Maven Prepare
        uses: optum/sourcehawk/.github/actions/maven-prepare@main
        with:
          cache-key-suffix: build-linux-distribution
          java-version: ${{ env.PRIMARY_JAVA_VERSION }}
      - name: Build Distribution
        if: success() && (github.event_name == 'pull_request')
        run: ./mvnw -B -U -D ci.build -D dist.build -pl distributions/${{ matrix.dist }} install
      - name: Build Distributions and Publish Snapshots
        if: success() && (github.event_name == 'push')
        run: ./mvnw -B -U -D ci.build -D ci.deploy -D ci.snapshot -D dist.build -pl distributions/${{ matrix.dist }} deploy
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Archive Distribution
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: linux-dist-${{ matrix.dist }}
          path: distributions/${{ matrix.dist }}/target/**

  build-mac-native-image:
    runs-on: macos-latest
    needs: build
    name: Build Native Image - Mac
    steps:
      - name: Build
        uses: optum/sourcehawk/.github/actions/build-native-image@main
        with:
          java-version: ${{ env.PRIMARY_JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: mac-native-image

  build-homebrew-tap-formula-archive:
    runs-on: macos-latest
    needs: build-mac-native-image
    name: Build Homebrew Tap Formula Archive
    steps:
      - name: Build
        uses: optum/sourcehawk/.github/actions/build-homebrew-tap-formula-archive@main

  build-windows-native-image:
    runs-on: windows-latest
    needs: build
    name: Build Native Image - Windows
    steps:
      - name: Build
        uses: optum/sourcehawk/.github/actions/build-windows-native-image@main
        with:
          java-version: ${{ env.PRIMARY_JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
