name: Update Native Image Builders

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Github Ref'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PACKAGE_TOKEN }}
      - name: Build and Push graalvm-ce-22.0.0-java11
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-nativeimage
          build-args: FROM_VERSION=ol8-java11-22.0.0.2-b1
          tags: ghcr.io/optum/ci/nativeimage:graalvm-ce-22.0.0-java11
          push: true
      - name: Build and Push graalvm-ce-22.0.0-java17
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: distributions/docker-builders/Dockerfile-nativeimage
          build-args: FROM_VERSION=ol8-java17-22.0.0.2-b1
          tags: ghcr.io/optum/ci/nativeimage:graalvm-ce-22.0.0-java17
          push: true
